# Generated by Django 3.0.4 on 2020-05-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0002_auto_20200507_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='gitlab_project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
