# Generated by Django 3.0.4 on 2020-05-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0003_project_gitlab_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='仓库名')),
                ('description', models.CharField(max_length=256, verbose_name='仓库说明')),
                ('vcs_type', models.SmallIntegerField(choices=[(1, 'git'), (2, 'svn')], verbose_name='版本库类型')),
                ('vcs_id', models.IntegerField(verbose_name='版本库ID')),
                ('vcs_url', models.CharField(max_length=512, verbose_name='版本库地址')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='gitlab_project_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=256, verbose_name='项目说明'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=64, verbose_name='项目名'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='服务名')),
                ('description', models.CharField(max_length=256, verbose_name='服务说明')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='deploy.Project', verbose_name='项目')),
                ('repository', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='deploy.Repository', verbose_name='版本仓库')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
    ]
