# Generated by Django 3.0.4 on 2020-05-14 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20200514_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='vcs_id',
        ),
        migrations.AddField(
            model_name='repository',
            name='vcs_project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='版本项目ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='项目说明'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='仓库说明'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='vcs_url',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='版本库地址'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='服务说明'),
        ),
        migrations.AlterField(
            model_name='service',
            name='repository',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='deploy.Repository', verbose_name='版本仓库'),
        ),
    ]
