# Generated by Django 3.0.4 on 2020-05-14 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0006_user_chinese_name'),
        ('ticket', '0015_auto_20200514_1055'),
        ('deploy', '0006_auto_20200514_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='部署项目名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='部署项目描述')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='deploy.Service', verbose_name='服务')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sys_mgr.Space', verbose_name='空间')),
            ],
            options={
                'verbose_name': '部署项目',
                'verbose_name_plural': '部署项目',
            },
        ),
        migrations.CreateModel(
            name='JobTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, verbose_name='部署任务名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='发布备注')),
                ('vcs_tag', models.CharField(blank=True, max_length=256, null=True, verbose_name='标签版本号')),
                ('type', models.SmallIntegerField(blank=True, default=0, verbose_name='部署方式')),
                ('created_type', models.SmallIntegerField(blank=True, default=0, verbose_name='创建类型')),
                ('status', models.SmallIntegerField(blank=True, default=0, verbose_name='状态')),
                ('detail_description', models.TextField(blank=True, null=True, verbose_name='部署任务详情')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execute_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='sys_mgr.User', verbose_name='执行人员')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='deploy.Job', verbose_name='部署项目')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='ticket.Ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '部署任务',
                'verbose_name_plural': '部署任务',
            },
        ),
    ]
