# Generated by Django 3.0.4 on 2020-05-14 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0007_job_jobtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '发布项目', 'verbose_name_plural': '发布项目'},
        ),
        migrations.AlterModelOptions(
            name='jobtask',
            options={'verbose_name': '发布任务', 'verbose_name_plural': '发布任务'},
        ),
        migrations.AddField(
            model_name='jobtask',
            name='number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='发布编号'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='发布项目描述'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='发布项目名'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='detail_description',
            field=models.TextField(blank=True, null=True, verbose_name='发布任务详情'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='deploy.Job', verbose_name='发布项目'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='name',
            field=models.CharField(default='', max_length=256, verbose_name='发布任务名'),
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='type',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='发布方式'),
        ),
    ]
