# Generated by Django 3.0.4 on 2020-05-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0006_user_chinese_name'),
        ('deploy', '0010_auto_20200514_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='sys_mgr.User', verbose_name='创建用户'),
        ),
    ]
