# Generated by Django 3.0.4 on 2020-05-15 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0012_auto_20200515_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobplan',
            name='number',
        ),
    ]
