# Generated by Django 3.0.4 on 2020-05-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0006_user_chinese_name'),
        ('deploy', '0013_remove_jobplan_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': '发布', 'verbose_name_plural': '发布'},
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='created_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '手动'), (2, '工单')], default=0, verbose_name='创建类型'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='job_type',
            field=models.SmallIntegerField(blank=True, choices=[(1, '手动'), (2, '自动')], default=0, verbose_name='发布方式'),
        ),
        migrations.CreateModel(
            name='JenkinsJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(default='', max_length=256, verbose_name='Jenkins-Job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenkins_jobs', to='deploy.Service', verbose_name='服务')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jenkins_jobs', to='sys_mgr.Space', verbose_name='空间')),
            ],
            options={
                'verbose_name': 'Jenkins-Job',
                'verbose_name_plural': 'Jenkins-Job',
            },
        ),
    ]
