# Generated by Django 3.0.4 on 2020-05-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0014_auto_20200515_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplan',
            name='vcs_tag',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='分支或标签版本号'),
        ),
    ]
