# Generated by Django 3.0.4 on 2020-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0015_auto_20200515_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobplan',
            name='status',
        ),
        migrations.AddField(
            model_name='jobplan',
            name='result',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='结果'),
        ),
    ]
