# Generated by Django 3.0.4 on 2020-05-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0016_auto_20200515_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobplan',
            old_name='result',
            new_name='status',
        ),
    ]
