# Generated by Django 3.0.4 on 2020-05-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0017_auto_20200515_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobplan',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='构建时间'),
        ),
    ]
