# Generated by Django 3.0.4 on 2020-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0018_jobplan_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobplan',
            name='console_output',
            field=models.TextField(blank=True, null=True, verbose_name='发布console信息'),
        ),
    ]
