# Generated by Django 3.0.4 on 2020-05-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0020_auto_20200516_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobplan',
            name='jenkins_build_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='jenkins构建号'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_plans', to='deploy.Job', verbose_name='发布'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='vcs_tag',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='分支或标签'),
        ),
    ]
