# Generated by Django 3.0.4 on 2020-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0021_auto_20200516_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplan',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='构建时长'),
        ),
    ]
