# Generated by Django 3.0.4 on 2020-05-19 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_tickettype_code'),
        ('sys_mgr', '0012_space_code'),
        ('deploy', '0022_auto_20200518_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobplan',
            name='execute_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_plans', to='sys_mgr.User', verbose_name='执行人员'),
        ),
        migrations.AlterField(
            model_name='jobplan',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_plans', to='ticket.Ticket', verbose_name='关联工单'),
        ),
    ]
