# Generated by Django 3.0.4 on 2020-05-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0003_menu_icon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='spaces',
            field=models.ManyToManyField(to='sys_mgr.Space'),
        ),
    ]
