# Generated by Django 3.0.4 on 2020-05-08 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0004_auto_20200507_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='部门名')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='职位名称')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sys_mgr.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ManyToManyField(to='sys_mgr.Position', verbose_name='职位'),
        ),
    ]
