# Generated by Django 3.0.4 on 2020-05-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0005_auto_20200508_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chinese_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='中文名'),
        ),
    ]
