# Generated by Django 3.0.4 on 2020-05-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0006_user_chinese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='code',
            field=models.CharField(default='', max_length=64),
        ),
    ]
