# Generated by Django 3.0.4 on 2020-05-18 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0008_auto_20200518_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='code',
        ),
    ]
