# Generated by Django 3.0.4 on 2020-05-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0010_space_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='code',
        ),
    ]
