# Generated by Django 3.0.4 on 2020-05-08 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploy', '0002_auto_20200507_1805'),
        ('sys_mgr', '0004_auto_20200507_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='类型名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='类型描述')),
            ],
            options={
                'verbose_name': '工单类型',
                'verbose_name_plural': '工单类型',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=256, verbose_name='主题')),
                ('vcs_tag', models.CharField(max_length=32, verbose_name='标签版本号')),
                ('service_conf', models.TextField(blank=True, null=True, verbose_name='更新服务配置')),
                ('db_conf', models.TextField(blank=True, null=True, verbose_name='更新数据库配置')),
                ('other_conf', models.TextField(blank=True, null=True, verbose_name='其他配置')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('audit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_audit_user', to='sys_mgr.User', verbose_name='审核人员')),
                ('execute_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_execute_user', to='sys_mgr.User', verbose_name='执行人员')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Project', verbose_name='项目名')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_space', to='sys_mgr.Space', verbose_name='空间')),
                ('test_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_test_user', to='sys_mgr.User', verbose_name='测试人员')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.TicketType', verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
            },
        ),
    ]
