# Generated by Django 3.0.4 on 2020-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200508_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='状态'),
        ),
    ]
