# Generated by Django 3.0.4 on 2020-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20200508_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='执行时间'),
        ),
    ]
