# Generated by Django 3.0.4 on 2020-05-08 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0006_user_chinese_name'),
        ('ticket', '0004_auto_20200508_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_create_user', to='sys_mgr.User', verbose_name='创建人员'),
        ),
    ]
