# Generated by Django 3.0.4 on 2020-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_create_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='audit_description',
            field=models.TextField(blank=True, null=True, verbose_name='审核意见'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='execute_description',
            field=models.TextField(blank=True, null=True, verbose_name='发布备注'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='test_description',
            field=models.TextField(blank=True, null=True, verbose_name='测试备注'),
        ),
    ]
