# Generated by Django 3.0.4 on 2020-05-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_ticket_cancel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vcs_tag',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='标签版本号'),
        ),
    ]
