# Generated by Django 3.0.4 on 2020-05-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20200513_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vcs_tag',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='标签版本号'),
        ),
    ]
