# Generated by Django 3.0.4 on 2020-05-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20200513_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='db_file',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='数据库文件'),
        ),
    ]
