# Generated by Django 3.0.4 on 2020-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_ticket_db_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='db_file',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='数据库文件'),
        ),
    ]
