# Generated by Django 3.0.4 on 2020-05-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20200513_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='工单号'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='db_conf',
            field=models.TextField(blank=True, null=True, verbose_name='数据库配置'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='db_file',
            field=models.FileField(blank=True, null=True, upload_to='sql/%Y/%m/%d/', verbose_name='数据库文件'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service_conf',
            field=models.TextField(blank=True, null=True, verbose_name='服务配置'),
        ),
    ]
