# Generated by Django 3.0.4 on 2020-05-13 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_auto_20200514_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, unique=True, verbose_name='工单编号'),
            preserve_default=False,
        ),
    ]
