# Generated by Django 3.0.4 on 2020-05-14 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0004_auto_20200514_0948'),
        ('ticket', '0013_auto_20200514_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.AddField(
            model_name='ticket',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='deploy.Service', verbose_name='服务名'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='工单编号'),
        ),
    ]
