# Generated by Django 3.0.4 on 2020-05-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20200514_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='vcs_tag',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='分支或标签'),
        ),
    ]
