# Generated by Django 3.0.4 on 2020-05-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20200515_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettype',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='代码'),
        ),
    ]
