# Generated by Django 3.0.4 on 2020-05-19 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sys_mgr', '0012_space_code'),
        ('deploy', '0023_auto_20200519_1307'),
        ('ticket', '0017_tickettype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketBindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bind_info_audit_user', to='sys_mgr.User', verbose_name='审核人员')),
                ('execute_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bind_info_execute_user', to='sys_mgr.User', verbose_name='执行人员')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deploy.Service', verbose_name='服务名')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bind_info_space', to='sys_mgr.Space', verbose_name='空间')),
                ('test_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bind_info_test_user', to='sys_mgr.User', verbose_name='测试人员')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bind_info', to='ticket.TicketType', verbose_name='工单类型')),
            ],
            options={
                'verbose_name': '工单绑定信息',
                'verbose_name_plural': '工单绑定信息',
            },
        ),
    ]
