# Generated by Django 3.0.4 on 2020-05-20 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_ticketbindinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_tickets', to='ticket.Ticket', verbose_name='父工单'),
        ),
    ]
